### ISSUE TITLE
Does Couchbase have to be in Docker?

### ISSUE THREAD

**Issue by mgroves** [metonymic-smokey/couchgres#1]
I'm trying out the migrate utility, moving from Postgres to Couchbase.

First thing I'm confused about is that `config.sh` requires a `CONTAINER_NAME`. Do I have to run Couchbase in a container? What if I'm just running it bare metal on Windows? Or on a cloud provider? Instead of `CONTAINER_NAME`, is there a "connection string" option I could use, like `CONNECTION_STRING="couchbase://localhost"`?

**Comment by metonymic-smokey** [comment]
@mgroves , thanks for trying it out!  

At the moment, yes, CB does have to be run as a container. I am working on making it compatible with it running as an application at the moment, should have it done in the next few days.  I shall keep you posted when that works.  

Thanks!

**Comment by metonymic-smokey** [comment]
@mgroves I have removed this dependency in my latest commits! Apologies for the delay, was a bit caught up with college.
Thanks!
