### ISSUE TITLE
I'm trying out the migrate utility, moving from Postgres to Couchbase.

### ISSUE THREAD

**Issue by mgroves** [metonymic-smokey/couchgres#2]
I'm trying out the migrate utility, moving from Postgres to Couchbase.

Also, I'm brand new to GoLang, so this is probably something obvious to any GoLong novice, but just following the README instructions, I run "go run db.go" and get the following error message:

```
PS C:\zproj\couchgres\migrate> go run db.go
db.go:15:2: cannot find package "github.com/jackc/pgx/v4" in any of:
        C:\Program Files\Go\src\github.com\jackc\pgx\v4 (from $GOROOT)
        C:\Users\mgroves\go\src\github.com\jackc\pgx\v4 (from $GOPATH)
```

I assume this means I have to install the pgx package somehow? But I'm not sure how to do that.

**Comment by metonymic-smokey** [comment]
@mgroves , thanks for pointing this out! Apologies for the incomplete instructions.

Yes, it does mean that.  
To install them, run : `go get -u "github.com/jackc/pgx"`,`go get -u "github.com/jackc/pgx/v4/"`, `go get -u "github.com/jackc/pgx/v4/pgxpool"`.  
I shall update the README instructions to reflect the same.

Thanks!
